#!/bin/bash
set -e

mysql -u root -p${MYSQL_ROOT_PASSWORD} -h $INSTANCE_PRIVATE_IP <<-EOSQL
  GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT
      ON *.* TO '${MYSQL_USER}'@'$'%';
  GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%';
  FLUSH PRIVILEGES;
EOSQL
